name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get update && sudo apt-get install -y musl-tools
      - uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3 # ratchet:dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.83.0
          targets: x86_64-unknown-linux-musl
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          repository: getzola/zola
          ref: ${{ github.ref }}
      - run: cargo build --target x86_64-unknown-linux-musl --release
      - run: file target/x86_64-unknown-linux-musl/release/zola
      - run: tar czf zola-${{ github.ref_name }}-x86_64-linux-musl.tar.gz -C target/x86_64-unknown-linux-musl/release zola
      - uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8 # ratchet:softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: zola-${{ github.ref_name }}-x86_64-linux-musl.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

